package net.kigawa.renlin.category

interface FlowFormAssociatedInteractivePalpablePhrasingIntersection : FlowContent, FormAssociatedContent, InteractiveContent, PalpableContent, PhrasingContent
interface FlowFormAssociatedInteractivePalpablePhrasingDsl<CATEGORY_DSL : FlowFormAssociatedInteractivePalpablePhrasingIntersection> :
    FlowContentDsl<CATEGORY_DSL>