#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx4096M
org.gradle.caching=true
#  https://github.com/gradle/gradle/issues/22779 le sigh
#org.gradle.configuration-cache=true
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64
#Kotlin
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
kotlin.compiler.incremental=true
kotlin.daemon.jvm.options=-Xskip-metadata-version-check

