package net.kigawa.renlin.w3c.category.native

import net.kigawa.renlin.w3c.category.ContentCategory

/**
 * Integration to EmbeddedFlowInteractivePalpablePhrasingIntegration, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingIntegration, EmbeddedFlowPalpablePhrasingIntegration
 * Parent: PhrasingContent
 */
interface EmbeddedContent : EmbeddedFlowInteractivePalpablePhrasingIntegration, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingIntegration, EmbeddedFlowPalpablePhrasingIntegration, ContentCategory, PhrasingContent