package net.kigawa.renlin.w3c.category.native

import net.kigawa.renlin.w3c.category.ContentCategory

/**
 * Integration to FlowMetadataPhrasingIntegration, FlowPalpableIntegration, FlowPalpableSectioningIntegration, FlowHeadingPalpableIntegration, FlowHeadingIntegration, FlowInteractivePalpablePhrasingIntegration, FlowPalpablePhrasingIntegration, FlowPhrasingIntegration, EmbeddedFlowInteractivePalpablePhrasingIntegration, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingIntegration, EmbeddedFlowPalpablePhrasingIntegration, FlowMetadataPhrasingScriptSupportingIntegration, FlowFormAssociatedInteractivePalpablePhrasingIntegration, AutocapitalizeInheritingFormFlowFormAssociatedPalpableIntegration, FlowFormAssociatedPalpablePhrasingIntegration, FlowInteractivePalpableIntegration
 * Parent: EventTarget
 */
interface FlowContent : FlowMetadataPhrasingIntegration, FlowPalpableIntegration, FlowPalpableSectioningIntegration, FlowHeadingPalpableIntegration, FlowHeadingIntegration, FlowInteractivePalpablePhrasingIntegration, FlowPalpablePhrasingIntegration, FlowPhrasingIntegration, EmbeddedFlowInteractivePalpablePhrasingIntegration, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingIntegration, EmbeddedFlowPalpablePhrasingIntegration, FlowMetadataPhrasingScriptSupportingIntegration, FlowFormAssociatedInteractivePalpablePhrasingIntegration, AutocapitalizeInheritingFormFlowFormAssociatedPalpableIntegration, FlowFormAssociatedPalpablePhrasingIntegration, FlowInteractivePalpableIntegration, ContentCategory, EventTarget