package net.kigawa.renlin.w3c.category.native

import net.kigawa.renlin.w3c.category.ContentCategory

/**
 * Union to FlowMetadataPhrasingUnion, FlowPalpableUnion, FlowPalpableSectioningUnion, FlowHeadingPalpableUnion, FlowHeadingUnion, FlowInteractivePalpablePhrasingUnion, FlowPalpablePhrasingUnion, FlowPhrasingUnion, EmbeddedFlowInteractivePalpablePhrasingUnion, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingUnion, EmbeddedFlowPalpablePhrasingUnion, FlowMetadataPhrasingScriptSupportingUnion, FlowFormAssociatedInteractivePalpablePhrasingUnion, AutocapitalizeInheritingFormFlowFormAssociatedPalpableUnion, FlowFormAssociatedPalpablePhrasingUnion, FlowInteractivePalpableUnion
 */
interface FlowContent :  FlowMetadataPhrasingUnion, FlowPalpableUnion, FlowPalpableSectioningUnion, FlowHeadingPalpableUnion, FlowHeadingUnion, FlowInteractivePalpablePhrasingUnion, FlowPalpablePhrasingUnion, FlowPhrasingUnion, EmbeddedFlowInteractivePalpablePhrasingUnion, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingUnion, EmbeddedFlowPalpablePhrasingUnion, FlowMetadataPhrasingScriptSupportingUnion, FlowFormAssociatedInteractivePalpablePhrasingUnion, AutocapitalizeInheritingFormFlowFormAssociatedPalpableUnion, FlowFormAssociatedPalpablePhrasingUnion, FlowInteractivePalpableUnion, ContentCategory