package net.kigawa.renlin.w3c.category.native

import net.kigawa.renlin.w3c.category.ContentCategory
import net.kigawa.renlin.w3c.category.native.HtmlCategory
import net.kigawa.renlin.w3c.category.native.HeadCategory
import net.kigawa.renlin.w3c.category.native.LinkCategory
import net.kigawa.renlin.w3c.category.native.MetaCategory
import net.kigawa.renlin.w3c.category.native.BodyCategory
import net.kigawa.renlin.w3c.category.native.AddressCategory
import net.kigawa.renlin.w3c.category.native.ArticleCategory
import net.kigawa.renlin.w3c.category.native.AsideCategory
import net.kigawa.renlin.w3c.category.native.FooterCategory
import net.kigawa.renlin.w3c.category.native.HeaderCategory
import net.kigawa.renlin.w3c.category.native.H1Category
import net.kigawa.renlin.w3c.category.native.H2Category
import net.kigawa.renlin.w3c.category.native.H3Category
import net.kigawa.renlin.w3c.category.native.H4Category
import net.kigawa.renlin.w3c.category.native.H5Category
import net.kigawa.renlin.w3c.category.native.H6Category
import net.kigawa.renlin.w3c.category.native.HgroupCategory
import net.kigawa.renlin.w3c.category.native.MainCategory
import net.kigawa.renlin.w3c.category.native.NavCategory
import net.kigawa.renlin.w3c.category.native.SectionCategory
import net.kigawa.renlin.w3c.category.native.SearchCategory
import net.kigawa.renlin.w3c.category.native.BlockquoteCategory
import net.kigawa.renlin.w3c.category.native.DdCategory
import net.kigawa.renlin.w3c.category.native.DivCategory
import net.kigawa.renlin.w3c.category.native.DlCategory
import net.kigawa.renlin.w3c.category.native.DtCategory
import net.kigawa.renlin.w3c.category.native.FigcaptionCategory
import net.kigawa.renlin.w3c.category.native.FigureCategory
import net.kigawa.renlin.w3c.category.native.HrCategory
import net.kigawa.renlin.w3c.category.native.LiCategory
import net.kigawa.renlin.w3c.category.native.MenuCategory
import net.kigawa.renlin.w3c.category.native.OlCategory
import net.kigawa.renlin.w3c.category.native.PCategory
import net.kigawa.renlin.w3c.category.native.PreCategory
import net.kigawa.renlin.w3c.category.native.UlCategory
import net.kigawa.renlin.w3c.category.native.ACategory
import net.kigawa.renlin.w3c.category.native.AbbrCategory
import net.kigawa.renlin.w3c.category.native.BCategory
import net.kigawa.renlin.w3c.category.native.BdiCategory
import net.kigawa.renlin.w3c.category.native.BdoCategory
import net.kigawa.renlin.w3c.category.native.BrCategory
import net.kigawa.renlin.w3c.category.native.CiteCategory
import net.kigawa.renlin.w3c.category.native.CodeCategory
import net.kigawa.renlin.w3c.category.native.DataCategory
import net.kigawa.renlin.w3c.category.native.DfnCategory
import net.kigawa.renlin.w3c.category.native.EmCategory
import net.kigawa.renlin.w3c.category.native.ICategory
import net.kigawa.renlin.w3c.category.native.KbdCategory
import net.kigawa.renlin.w3c.category.native.MarkCategory
import net.kigawa.renlin.w3c.category.native.QCategory
import net.kigawa.renlin.w3c.category.native.RpCategory
import net.kigawa.renlin.w3c.category.native.RtCategory
import net.kigawa.renlin.w3c.category.native.RubyCategory
import net.kigawa.renlin.w3c.category.native.SCategory
import net.kigawa.renlin.w3c.category.native.SampCategory
import net.kigawa.renlin.w3c.category.native.SmallCategory
import net.kigawa.renlin.w3c.category.native.SpanCategory
import net.kigawa.renlin.w3c.category.native.StrongCategory
import net.kigawa.renlin.w3c.category.native.SubCategory
import net.kigawa.renlin.w3c.category.native.SupCategory
import net.kigawa.renlin.w3c.category.native.TimeCategory
import net.kigawa.renlin.w3c.category.native.UCategory
import net.kigawa.renlin.w3c.category.native.VarCategory
import net.kigawa.renlin.w3c.category.native.WbrCategory
import net.kigawa.renlin.w3c.category.native.AreaCategory
import net.kigawa.renlin.w3c.category.native.AudioCategory
import net.kigawa.renlin.w3c.category.native.ImgCategory
import net.kigawa.renlin.w3c.category.native.MapCategory
import net.kigawa.renlin.w3c.category.native.TrackCategory
import net.kigawa.renlin.w3c.category.native.VideoCategory
import net.kigawa.renlin.w3c.category.native.EmbedCategory
import net.kigawa.renlin.w3c.category.native.FencedframeCategory
import net.kigawa.renlin.w3c.category.native.IframeCategory
import net.kigawa.renlin.w3c.category.native.ObjectCategory
import net.kigawa.renlin.w3c.category.native.PictureCategory
import net.kigawa.renlin.w3c.category.native.SourceCategory
import net.kigawa.renlin.w3c.category.native.SvgCategory
import net.kigawa.renlin.w3c.category.native.MathCategory
import net.kigawa.renlin.w3c.category.native.CanvasCategory
import net.kigawa.renlin.w3c.category.native.NoscriptCategory
import net.kigawa.renlin.w3c.category.native.ScriptCategory
import net.kigawa.renlin.w3c.category.native.DelCategory
import net.kigawa.renlin.w3c.category.native.InsCategory
import net.kigawa.renlin.w3c.category.native.CaptionCategory
import net.kigawa.renlin.w3c.category.native.ColCategory
import net.kigawa.renlin.w3c.category.native.ColgroupCategory
import net.kigawa.renlin.w3c.category.native.TableCategory
import net.kigawa.renlin.w3c.category.native.TbodyCategory
import net.kigawa.renlin.w3c.category.native.TdCategory
import net.kigawa.renlin.w3c.category.native.TfootCategory
import net.kigawa.renlin.w3c.category.native.ThCategory
import net.kigawa.renlin.w3c.category.native.TheadCategory
import net.kigawa.renlin.w3c.category.native.TrCategory
import net.kigawa.renlin.w3c.category.native.ButtonCategory
import net.kigawa.renlin.w3c.category.native.DatalistCategory
import net.kigawa.renlin.w3c.category.native.FieldsetCategory
import net.kigawa.renlin.w3c.category.native.FormCategory
import net.kigawa.renlin.w3c.category.native.InputCategory
import net.kigawa.renlin.w3c.category.native.LabelCategory
import net.kigawa.renlin.w3c.category.native.LegendCategory
import net.kigawa.renlin.w3c.category.native.MeterCategory
import net.kigawa.renlin.w3c.category.native.OptgroupCategory
import net.kigawa.renlin.w3c.category.native.OptionCategory
import net.kigawa.renlin.w3c.category.native.OutputCategory
import net.kigawa.renlin.w3c.category.native.ProgressCategory
import net.kigawa.renlin.w3c.category.native.SelectCategory
import net.kigawa.renlin.w3c.category.native.SelectedcontentCategory
import net.kigawa.renlin.w3c.category.native.TextareaCategory
import net.kigawa.renlin.w3c.category.native.DetailsCategory
import net.kigawa.renlin.w3c.category.native.DialogCategory
import net.kigawa.renlin.w3c.category.native.SummaryCategory
import net.kigawa.renlin.w3c.category.native.SlotCategory
import net.kigawa.renlin.w3c.category.native.TemplateCategory

/**
 * FlowContent represents elements that are part of the flow content category.
 * Parent: P, Div
 */
interface FlowContent : ContentCategory, P, Div, HtmlCategory, HeadCategory, LinkCategory, MetaCategory, BodyCategory, AddressCategory, ArticleCategory, AsideCategory, FooterCategory, HeaderCategory, H1Category, H2Category, H3Category, H4Category, H5Category, H6Category, HgroupCategory, MainCategory, NavCategory, SectionCategory, SearchCategory, BlockquoteCategory, DdCategory, DivCategory, DlCategory, DtCategory, FigcaptionCategory, FigureCategory, HrCategory, LiCategory, MenuCategory, OlCategory, PCategory, PreCategory, UlCategory, ACategory, AbbrCategory, BCategory, BdiCategory, BdoCategory, BrCategory, CiteCategory, CodeCategory, DataCategory, DfnCategory, EmCategory, ICategory, KbdCategory, MarkCategory, QCategory, RpCategory, RtCategory, RubyCategory, SCategory, SampCategory, SmallCategory, SpanCategory, StrongCategory, SubCategory, SupCategory, TimeCategory, UCategory, VarCategory, WbrCategory, AreaCategory, AudioCategory, ImgCategory, MapCategory, TrackCategory, VideoCategory, EmbedCategory, FencedframeCategory, IframeCategory, ObjectCategory, PictureCategory, SourceCategory, SvgCategory, MathCategory, CanvasCategory, NoscriptCategory, ScriptCategory, DelCategory, InsCategory, CaptionCategory, ColCategory, ColgroupCategory, TableCategory, TbodyCategory, TdCategory, TfootCategory, ThCategory, TheadCategory, TrCategory, ButtonCategory, DatalistCategory, FieldsetCategory, FormCategory, InputCategory, LabelCategory, LegendCategory, MeterCategory, OptgroupCategory, OptionCategory, OutputCategory, ProgressCategory, SelectCategory, SelectedcontentCategory, TextareaCategory, DetailsCategory, DialogCategory, SummaryCategory, SlotCategory, TemplateCategory