package net.kigawa.renlin.w3c.category.native

import net.kigawa.renlin.w3c.category.ContentCategory
import net.kigawa.renlin.w3c.category.union.EmbeddedFlowFormAssociatedInteractivePalpablePhrasingUnion
import net.kigawa.renlin.w3c.category.union.FlowFormAssociatedInteractivePalpablePhrasingUnion
import net.kigawa.renlin.w3c.category.union.AutocapitalizeInheritingFormFlowFormAssociatedPalpableUnion
import net.kigawa.renlin.w3c.category.union.FlowFormAssociatedPalpablePhrasingUnion

/**
 * Union to EmbeddedFlowFormAssociatedInteractivePalpablePhrasingUnion, FlowFormAssociatedInteractivePalpablePhrasingUnion, AutocapitalizeInheritingFormFlowFormAssociatedPalpableUnion, FlowFormAssociatedPalpablePhrasingUnion
 */
interface FormAssociatedContentContent :  EmbeddedFlowFormAssociatedInteractivePalpablePhrasingUnion, FlowFormAssociatedInteractivePalpablePhrasingUnion, AutocapitalizeInheritingFormFlowFormAssociatedPalpableUnion, FlowFormAssociatedPalpablePhrasingUnion, ContentCategory