package net.kigawa.renlin.w3c.category.native

import net.kigawa.renlin.w3c.category.ContentCategory

/**
 * Integration to FlowInteractivePalpablePhrasingIntegration, EmbeddedFlowInteractivePalpablePhrasingIntegration, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingIntegration, FlowFormAssociatedInteractivePalpablePhrasingIntegration, FlowInteractivePalpableIntegration
 * Parent: PhrasingContent
 */
interface InteractiveContent : FlowInteractivePalpablePhrasingIntegration, EmbeddedFlowInteractivePalpablePhrasingIntegration, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingIntegration, FlowFormAssociatedInteractivePalpablePhrasingIntegration, FlowInteractivePalpableIntegration, ContentCategory, PhrasingContent