package net.kigawa.renlin.w3c.category.native

import net.kigawa.renlin.w3c.category.ContentCategory

/**
 * Union to FlowPalpableUnion, FlowPalpableSectioningUnion, FlowHeadingPalpableUnion, FlowInteractivePalpablePhrasingUnion, FlowPalpablePhrasingUnion, EmbeddedFlowInteractivePalpablePhrasingUnion, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingUnion, EmbeddedFlowPalpablePhrasingUnion, FlowFormAssociatedInteractivePalpablePhrasingUnion, AutocapitalizeInheritingFormFlowFormAssociatedPalpableUnion, FlowFormAssociatedPalpablePhrasingUnion, FlowInteractivePalpableUnion
 */
interface PalpableContent :  FlowPalpableUnion, FlowPalpableSectioningUnion, FlowHeadingPalpableUnion, FlowInteractivePalpablePhrasingUnion, FlowPalpablePhrasingUnion, EmbeddedFlowInteractivePalpablePhrasingUnion, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingUnion, EmbeddedFlowPalpablePhrasingUnion, FlowFormAssociatedInteractivePalpablePhrasingUnion, AutocapitalizeInheritingFormFlowFormAssociatedPalpableUnion, FlowFormAssociatedPalpablePhrasingUnion, FlowInteractivePalpableUnion, ContentCategory