package net.kigawa.renlin.w3c.category.native

import net.kigawa.renlin.w3c.category.ContentCategory

/**
 * Integration to FlowPalpableIntegration, FlowPalpableSectioningIntegration, FlowHeadingPalpableIntegration, FlowInteractivePalpablePhrasingIntegration, FlowPalpablePhrasingIntegration, EmbeddedFlowInteractivePalpablePhrasingIntegration, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingIntegration, EmbeddedFlowPalpablePhrasingIntegration, FlowFormAssociatedInteractivePalpablePhrasingIntegration, AutocapitalizeInheritingFormFlowFormAssociatedPalpableIntegration, FlowFormAssociatedPalpablePhrasingIntegration, FlowInteractivePalpableIntegration
 * 
 */
interface PalpableContent : FlowPalpableIntegration, FlowPalpableSectioningIntegration, FlowHeadingPalpableIntegration, FlowInteractivePalpablePhrasingIntegration, FlowPalpablePhrasingIntegration, EmbeddedFlowInteractivePalpablePhrasingIntegration, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingIntegration, EmbeddedFlowPalpablePhrasingIntegration, FlowFormAssociatedInteractivePalpablePhrasingIntegration, AutocapitalizeInheritingFormFlowFormAssociatedPalpableIntegration, FlowFormAssociatedPalpablePhrasingIntegration, FlowInteractivePalpableIntegration, ContentCategory