package net.kigawa.renlin.w3c.category.native

import net.kigawa.renlin.w3c.category.ContentCategory
import net.kigawa.renlin.w3c.category.union.FlowPalpableUnion
import net.kigawa.renlin.w3c.category.union.FlowPalpableSectioningUnion
import net.kigawa.renlin.w3c.category.union.FlowHeadingPalpableUnion
import net.kigawa.renlin.w3c.category.union.FlowInteractivePalpablePhrasingUnion
import net.kigawa.renlin.w3c.category.union.FlowPalpablePhrasingUnion
import net.kigawa.renlin.w3c.category.union.EmbeddedFlowInteractivePalpablePhrasingUnion
import net.kigawa.renlin.w3c.category.union.EmbeddedFlowFormAssociatedInteractivePalpablePhrasingUnion
import net.kigawa.renlin.w3c.category.union.EmbeddedFlowPalpablePhrasingUnion
import net.kigawa.renlin.w3c.category.union.FlowFormAssociatedInteractivePalpablePhrasingUnion
import net.kigawa.renlin.w3c.category.union.AutocapitalizeInheritingFormFlowFormAssociatedPalpableUnion
import net.kigawa.renlin.w3c.category.union.FlowFormAssociatedPalpablePhrasingUnion
import net.kigawa.renlin.w3c.category.union.FlowInteractivePalpableUnion

/**
 * Union to FlowPalpableUnion, FlowPalpableSectioningUnion, FlowHeadingPalpableUnion, FlowInteractivePalpablePhrasingUnion, FlowPalpablePhrasingUnion, EmbeddedFlowInteractivePalpablePhrasingUnion, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingUnion, EmbeddedFlowPalpablePhrasingUnion, FlowFormAssociatedInteractivePalpablePhrasingUnion, AutocapitalizeInheritingFormFlowFormAssociatedPalpableUnion, FlowFormAssociatedPalpablePhrasingUnion, FlowInteractivePalpableUnion
 */
interface PalpableContentContent :  FlowPalpableUnion, FlowPalpableSectioningUnion, FlowHeadingPalpableUnion, FlowInteractivePalpablePhrasingUnion, FlowPalpablePhrasingUnion, EmbeddedFlowInteractivePalpablePhrasingUnion, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingUnion, EmbeddedFlowPalpablePhrasingUnion, FlowFormAssociatedInteractivePalpablePhrasingUnion, AutocapitalizeInheritingFormFlowFormAssociatedPalpableUnion, FlowFormAssociatedPalpablePhrasingUnion, FlowInteractivePalpableUnion, ContentCategory