package net.kigawa.renlin.w3c.category.native

import net.kigawa.renlin.w3c.category.ContentCategory

/**
 * Integration to FlowMetadataPhrasingIntegration, FlowInteractivePalpablePhrasingIntegration, FlowPalpablePhrasingIntegration, FlowPhrasingIntegration, EmbeddedFlowInteractivePalpablePhrasingIntegration, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingIntegration, EmbeddedFlowPalpablePhrasingIntegration, FlowMetadataPhrasingScriptSupportingIntegration, FlowFormAssociatedInteractivePalpablePhrasingIntegration, FlowFormAssociatedPalpablePhrasingIntegration
 * Parent: FlowContent
 */
interface PhrasingContent : FlowMetadataPhrasingIntegration, FlowInteractivePalpablePhrasingIntegration, FlowPalpablePhrasingIntegration, FlowPhrasingIntegration, EmbeddedFlowInteractivePalpablePhrasingIntegration, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingIntegration, EmbeddedFlowPalpablePhrasingIntegration, FlowMetadataPhrasingScriptSupportingIntegration, FlowFormAssociatedInteractivePalpablePhrasingIntegration, FlowFormAssociatedPalpablePhrasingIntegration, ContentCategory, FlowContent