package net.kigawa.renlin.w3c.category.native

import net.kigawa.renlin.w3c.category.ContentCategory
import net.kigawa.renlin.w3c.category.union.FlowMetadataPhrasingUnion
import net.kigawa.renlin.w3c.category.union.FlowInteractivePalpablePhrasingUnion
import net.kigawa.renlin.w3c.category.union.FlowPalpablePhrasingUnion
import net.kigawa.renlin.w3c.category.union.FlowPhrasingUnion
import net.kigawa.renlin.w3c.category.union.EmbeddedFlowInteractivePalpablePhrasingUnion
import net.kigawa.renlin.w3c.category.union.EmbeddedFlowFormAssociatedInteractivePalpablePhrasingUnion
import net.kigawa.renlin.w3c.category.union.EmbeddedFlowPalpablePhrasingUnion
import net.kigawa.renlin.w3c.category.union.FlowMetadataPhrasingScriptSupportingUnion
import net.kigawa.renlin.w3c.category.union.FlowFormAssociatedInteractivePalpablePhrasingUnion
import net.kigawa.renlin.w3c.category.union.FlowFormAssociatedPalpablePhrasingUnion

/**
 * Union to FlowMetadataPhrasingUnion, FlowInteractivePalpablePhrasingUnion, FlowPalpablePhrasingUnion, FlowPhrasingUnion, EmbeddedFlowInteractivePalpablePhrasingUnion, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingUnion, EmbeddedFlowPalpablePhrasingUnion, FlowMetadataPhrasingScriptSupportingUnion, FlowFormAssociatedInteractivePalpablePhrasingUnion, FlowFormAssociatedPalpablePhrasingUnion
 */
interface PhrasingContentContent :  FlowMetadataPhrasingUnion, FlowInteractivePalpablePhrasingUnion, FlowPalpablePhrasingUnion, FlowPhrasingUnion, EmbeddedFlowInteractivePalpablePhrasingUnion, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingUnion, EmbeddedFlowPalpablePhrasingUnion, FlowMetadataPhrasingScriptSupportingUnion, FlowFormAssociatedInteractivePalpablePhrasingUnion, FlowFormAssociatedPalpablePhrasingUnion, ContentCategory