package net.kigawa.renlin.w3c.category.native

import net.kigawa.renlin.w3c.category.ContentCategory

/**
 * Union to FlowMetadataPhrasingUnion, FlowInteractivePalpablePhrasingUnion, FlowPalpablePhrasingUnion, FlowPhrasingUnion, EmbeddedFlowInteractivePalpablePhrasingUnion, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingUnion, EmbeddedFlowPalpablePhrasingUnion, FlowMetadataPhrasingScriptSupportingUnion, FlowFormAssociatedInteractivePalpablePhrasingUnion, FlowFormAssociatedPalpablePhrasingUnion
 * Parent: FlowContent
 */
interface PhrasingContent : FlowMetadataPhrasingUnion, FlowInteractivePalpablePhrasingUnion, FlowPalpablePhrasingUnion, FlowPhrasingUnion, EmbeddedFlowInteractivePalpablePhrasingUnion, EmbeddedFlowFormAssociatedInteractivePalpablePhrasingUnion, EmbeddedFlowPalpablePhrasingUnion, FlowMetadataPhrasingScriptSupportingUnion, FlowFormAssociatedInteractivePalpablePhrasingUnion, FlowFormAssociatedPalpablePhrasingUnion, ContentCategory, FlowContent